name: update cocomanhua keys

on:
  schedule:
    - cron: '0 0/8 * * *'
  workflow_dispatch:
  watch:
    types: [ started ]

jobs:
  updateKeys:
    runs-on: ubuntu-latest
    steps:

      - name: fetch source
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          cd /workdir
          pwd

      - name: Clone source code
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone -b dependabot/npm_and_yarn/puppeteer-17.1.1 --single-branch --depth 1  https://github.com/Xwite/autoCI.git autoCI
          cd autoCI
          pwd
          ls -l -h
          ln -sf $PWD $GITHUB_WORKSPACE/autoCI
          echo "WORK_DIR=$PWD" >> $GITHUB_ENV
          ls -l -h /workdir/autoCI/requirements.txt
          ls -l -h /workdir/autoCI/package.json
          
          echo "requirements : ${{ hashFiles('/workdir/autoCI/requirements.txt') }}"
          echo "package : ${{ hashFiles('/workdir/autoCI/package.json') }}"
          
          echo "requirements : ${{ hashFiles('/workdir/autoCI/**/requirements.txt') }}"
          echo "package : ${{ hashFiles('/workdir/autoCI/**/package.json') }}"
          
          echo "requirements : ${{ hashFiles('/workdir/**/requirements.txt') }}"
          echo "package : ${{ hashFiles('/workdir/**/package.json') }}"
          
          echo "requirements : ${{ hashFiles('**/requirements.txt') }}"
          echo "package : ${{ hashFiles('**/package.json') }}"
          
          echo "requirements : ${{ hashFiles('requirements.txt') }}"
          echo "package : ${{ hashFiles('package.json') }}"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.local/lib/python3.8/site-packages
            ./node_modules
          key: ${{ runner.os }}-autoCI-${{ hashFiles('/workdir/autoCI/requirements.txt') }}-${{ hashFiles('/workdir/autoCI/package.json') }}
          restore-keys: |
            ${{ runner.os }}-autoCI-${{ hashFiles('/workdir/autoCI/requirements.txt') }}-${{ hashFiles('/workdir/autoCI/package.json') }}


      - name: extra keys
        run: |
          cd ${{ env.WORK_DIR }}
          source ./coco/coco.sh
          main
      - name: move keys to ./autoBuild
        run: |
          cd ${{ env.WORK_DIR }}
          mv coco_keys.json ./autoBuild

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: 'update cocomanga keys at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M:%S")'
          branch: autoBuild
          repository: ${{ env.WORK_DIR }}/autoBuild
          file_pattern: coco_keys.json
          skip_checkout: false
          create_branch: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
