name: update cocomanhua keys

on:
  schedule:
    - cron: '0 0/8 * * *'
  workflow_dispatch:
  watch:
    types: [started]
  
jobs:
  updateKeys:
    runs-on: ubuntu-latest
    steps:
          
      - name: fetch source
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          cd /workdir
          pwd
          
      - name: Clone source code
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone -b dependabot/npm_and_yarn/puppeteer-17.1.1 --single-branch --depth 1  https://github.com/Xwite/autoCI.git autoCI
          ln -sf /workdir/autoCI $GITHUB_WORKSPACE/autoCI

      - uses: actions/cache@v3
        working-directory: /workdir
        with:
          path: |
            ~/.local/lib/python3.8/site-packages
            ./node_modules
          key: ${{ runner.os }}-autoCI-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-autoCI-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/package.json') }}
          

      - name: extra keys
        working-directory: /workdir
        run: |
          source ./coco/coco.sh
          main
      - name: move keys to ./autoBuild
        working-directory: /workdir
        run: mv coco_keys.json ./autoBuild

      - name: push changes
        working-directory: /workdir
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: 'update cocomanhua keys at $(TZ=UTC-8 date +"%Y-%m-%d %H:%M:%S")'
          branch: autoBuild
          repository: ./autoBuild
          file_pattern: coco_keys.json
          skip_checkout: false
          create_branch: true

      - name: Delete workflow runs
        working-directory: /workdir
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
